version: "3.7"

services:
  node:
    build: ./../
    container_name: node
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    links:
      - mongodb
    env_file:
        - .env_docker
  mongodb:
    build: ./mongodb
    container_name: mongo
    ports:
      - 27017-27019:27017-27019
    volumes:
      - ./mongodb/mongo-volume:/data/db
  ngrok:
    image: wernight/ngrok
    container_name: ngrok
    ports:
      - 4040:4040
    links:
      - node
    depends_on:
      - node
    env_file:
      - .env_docker
